
'use client'

import { useTransition, useState } from 'react'
import { deleteTemplate } from '@/app/actions/templates'
import toast from 'react-hot-toast'
import Modal from '@/components/Modal'

export default function TemplateDeleteButton({ id }: { id: string }) {
  const [isPending, startTransition] = useTransition()
  const [showModal, setShowModal] = useState(false)
  
  const handleDelete = () => {
    startTransition(async () => {
      try {
        await deleteTemplate(id)
        toast.success('Template deleted')
        setShowModal(false)
      } catch (e: any) {
        toast.error(e.message)
      }
    })
  }

  return (
    <>
      <button
        onClick={() => setShowModal(true)}
        disabled={isPending}
        className="text-[10px] tracking-widest uppercase text-red-500/70 hover:text-red-700 transition-colors disabled:opacity-50"
      >
        {isPending ? '...' : 'Remove'}
      </button>
      
      {showModal && (
        <Modal title="Delete Template" onClose={() => setShowModal(false)} maxWidth="max-w-md">
          <p className="text-[var(--foreground)] mb-6 text-sm">
            Are you sure you want to delete this template? 
          </p>
          <p className="text-[var(--foreground-muted)] mb-8 text-sm">
            This will permanently remove the template and delete all future empty classes generated by it.
          </p>
          <div className="flex gap-4 justify-end">
            <button 
              onClick={() => setShowModal(false)}
              className="px-6 py-2 rounded-full text-xs uppercase tracking-widest text-[var(--foreground-muted)] hover:bg-black/5"
            >
              Cancel
            </button>
            <button 
              onClick={handleDelete}
              disabled={isPending}
              className="px-6 py-2 rounded-full text-xs uppercase tracking-widest bg-red-600 text-white hover:bg-red-700 disabled:opacity-50"
            >
              {isPending ? 'Deleting...' : 'Delete Template'}
            </button>
          </div>
        </Modal>
      )}
    </>
  )
}
